version: '3'
services:
  api:
    container_name: taskapi_re
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - .dockerenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true
    tty: true
    #entrypoint: ["bash"]
    
  postgresql:
    image: postgres:14
    container_name: postgres_re
    environment:
      POSTGRES_DB: task_data
      POSTGRES_USER: kaneko
      POSTGRES_PASSWORD: goldsilver
      TZ: Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - 5432:5432

  web:
    container_name: front
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
    - .frontend:/src/.venv
    ports: 
    - 3000:3000
    environment: 
      TZ: Asia/Tokyo
    tty: true

volumes:
  dockerenv:
    driver: local
  postgres_data:
    driver: local
  frontend:
    driver: local