version: '3'
services:
  api:
    container_name: task_api
    build: .
    volumes:
      - .dockerenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    environment:
    - WATCHFILES_FORCE_POLLING=true

volumes:
  dockerenv: 
    driver: local
    